### ISSUE TITLE
Error en invocación de variable

### ISSUE THREAD

**Issue by IvanCoronel** [padiazg/scrapper-example#2]
![captura de pantalla de 2018-09-14 14-23-20](https://user-images.githubusercontent.com/7606278/45569422-77ef2300-b82d-11e8-8399-5ad021a73709.png)
En el script basedatos.js se declara una constante addCedula(linea 3), que luego se invoca para  agregar los datos a la colección como addCedulaSafe(linea 21). Por lo que da un error de variable no definida.

**Comment by padiazg** [comment]
Corregido en pull request #4 
Se agradece el feedback.
