### ISSUE TITLE
Error Conexion BD 

### ISSUE THREAD

**Issue by IvanCoronel** [padiazg/scrapper-example#3]
![ejecuxion basedatos js](https://user-images.githubusercontent.com/7606278/45569661-2e530800-b82e-11e8-8902-c2940c55dd5d.png)
En el momento de ejecutar el script basedatos.js, previamente de seguir las instrucciones de readme.md y mongodb-docker.md. Da un error de autenticación a la base de datos, no se si en el mismo script después de instanciar (const mongoose = require("mongoose")) deberia tambien autenticarse con algun password y contraseña.

**Comment by padiazg** [comment]
Corregido en pull request #4 
Agradecido por el feedback.
